default:
  disable: false
  type: mysql
  node:
    - path: 127.0.0.1
      port: "3306"
      database: user-center
      username: root
      password: "123456"
      role: true
    - path: 127.0.0.1
      port: "3306"
      database: user-center
      username: root
      password: "123456"
      role: false
  maxIdleConns: 10
  maxOpenConns: 100
  logLevel: info
  log: false
